gato2020/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('add/', views.add_product, name='add_product'),
]

gato2020/urls.py
from django.contrib import admin
from django.urls import path, include

from gato2020 import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('main/', include('gato2020.main.urls')),
    path('products/', include('gato2020.products.urls')),
    path('profiles/', include('gato2020.profiles.urls')),
    path('map/', include('gato2020.map.urls')),
    path('clients/', include('gato2020.clients.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gato2020/products/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.core.exceptions import ValidationError

class ProductCategory(models.Model):
    name = models.CharField(
        max_length=20
    )

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        null=False,
        blank=False
    )

    name = models.CharField(
        max_length=100,
        null=False,
        blank=False
    )

    package_weight = models.DecimalField(
        max_digits=4,
        decimal_places=3,
        null=False,
        blank=False
    )

    arabica = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Percentage of arabica content"
    )

    robusta = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Percentage of arabica content"
    )

    image = models.ImageField(
        upload_to='products/images/',
        null=False,
        blank=False
    )

    origin = models.CharField(
        max_length=100,
        null=True,
        blank=True
    )

    description = models.TextField(
        null=True,
        blank=True,
        help_text="Write short description"
    )

    def __str__(self):
        return self.name

    def clean(self):
        if self.category.name == 'кафе на зърна':
            if not self.origin:
                raise ValidationError("Origin is required for coffee products")

            if self.arabica is not None and self.robusta is not None:
                raise ValidationError("Only one of Arabica or Robusta percentage should be provided")

            if self.arabica is not None:
                if self.arabica == 0:
                    self.robusta = 100
                else:
                    self.robusta = 100 - self.arabica

            elif self.robusta is not None:
                if self.robusta == 0:
                    self.arabica = 100
                else:
                    self.arabica = 100 - self.robusta

            else:
                raise ValidationError("Arabica/Robusta percentage is required for coffee products")

        elif self.category.name != 'кафе на зърна':

            if self.origin:
                raise ValidationError("Origin should not be provided for non-coffee products")

            if self.arabica:
                raise ValidationError("Arabica percentage should not be provided for non-coffee products")

            if self.robusta:
                raise ValidationError("Robusta percentage should not be provided for non-coffee products")

gato2020/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'name', 'package_weight', 'image', 'origin', 'arabica', 'robusta', 'description']

gato2020/products/views.py
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from .models import Product
from .forms import ProductForm

@staff_member_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm()
    return render(request, 'products/add_product.html', {'form': form})


def product_list(request):
    products = Product.objects.all()
    return render(request, 'products/product_list.html', {'products': products})

templates/products/add_product.html
{% extends 'base.html' %}
{% load static %}
{% block main_content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="mb-4">Добави продукт:</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_category">Категория:</label>
                    {{ form.category }}
                </div>
                <div class="form-group">
                    <label for="id_name">Име:</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    <label for="id_package_weight">Кг/пакет:</label>
                    {{ form.package_weight }}
                </div>
                <div class="form-group">
                    <label for="id_arabica">Арабика (%):</label>
                    {{ form.arabica }}
                </div>
                <div class="form-group">
                    <label for="id_robusta">Робуста (%):</label>
                    {{ form.robusta }}
                </div>
                <div class="form-group">
                    <label for="id_image">Изображение:</label>
                    {{ form.image }}
                </div>
                <div class="form-group">
                    <label for="id_origin">Произход:</label>
                    {{ form.origin }}
                </div>
                <div class="form-group">
                    <label for="id_description">Описание:</label>
                    {{ form.description }}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Запази</button> 
            </form>
        </div>
    </div>
</div>
    

{% endblock %}

{% block footer %}
<footer class="bg-dark text-white py-3 fixed-bottom" style="z-index: 1000;">
    <div class="container">
        <div class="row">
            <div class="col">
                <p class="mb-0">© 2024 Примерен Уеб Сайт. Всички права запазени.</p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

templates/products/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}
<div class="container text-center mb-4"> 
    <h1 class="mt-5 mb-4" style="font-size: 26px;">Открийте нашата богата селекция от Нестле продукти, предлагани от Гато 2020</h1>
    <p style="font-size: 20px;">Независимо дали сте хотелиер, ресторантьор или офис мениджър, нашите кафе, напитки и машини са точното решение за вашите нужди. Разгледайте нашата гама и открийте любимите си брандове на Нестле!</p>
</div>

<div class="container">

    <div class="row" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); grid-gap: 20px;">
        {% for product in products %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5> 
                <img src="{{ product.image.url }}" class="card-img-top mx-auto d-block" alt="{{ product.name }}" style="width: 100%; height: 350px; object-fit: cover;">
                <p class="card-text">Категория: {{ product.category }}</p>
                <p class="card-text">Кг/пакет: {{ product.package_weight }}</p>
                {% if product.origin %}
                <p class="card-text">Произход: {{ product.origin }}</p>
                {% endif %}
                {% if product.arabica %}
                <p class="card-text">Арабика: {{ product.arabica }}%</p>
                {% endif %}
                {% if product.robusta %}
                <p class="card-text">Робуста: {{ product.robusta }}%</p>
                {% endif %}
                <p class="card-text">Описание: {{ product.description }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="container mt-4">
    <div class="text-left"> 
        {% if request.user.is_superuser %}
            <a href="{% url 'add_product' %}" class="btn btn-primary">Добави нов продукт</a>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block footer %}
<footer class="bg-dark text-white py-3 fixed-bottom">
    <div class="container">
        <div class="row">
            <div class="col">
                <p>© 2024 Примерен Уеб Сайт. Всички права запазени.</p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}